title: Colquitt Lab at UCSC
description:
logo-text: true
header: images/black.png
footer: images/black.png
header-dark: true
baseurl: ""
links:
  email: colquitt@ucsc.edu
  google-scholar: wkjT3poAAAAJ
  github: colquittlab
  twitter: bradleycolquitt
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
google_analytics: G-FXFJBRMJ2R
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
