
- id: doi:10.7554/eLife.85970
  image: images/colquitt_2023_elife_network.png

- id: doi:10.1159/000525019
  image: images/motor_evolution_short.svg

- id: doi:10.1126/science.abd9704
  image: images/science_summary.svg

- id: doi:10.1093/gigascience/giy008
  image: images/BF_pic.png

- id: doi:10.1016/j.neuron.2014.07.013
  image: images/neuron_dhs.svg

- id: doi:10.1016/j.cell.2014.09.033

- id: doi:10.1073/pnas.1302759110
  image: images/Colquitt_2014_PNAS_gene-profile.png
  
- id: doi:10.1016/j.cell.2011.03.040
